export const API_ENDPOINTS = {
  LOGIN: '/auth/login',
  REGISTER: '/auth/register',
  SEND_VERIFICATION: '/auth/send-verification',
  VERIFY_EMAIL: 'auth/verify-email',
  LOGOUT: '/',
  USER_PROFILE: '/users/profile',
  FORGET_PASSWORD: '/',
  SHIPPING_ADDRESS: '/shipping-addresses',
  CATEGORIES: '/product-categories/sub-categories',
  DIETARY: '/',
  BRANDS: '/brands',
  FLEX_PRODUCTS: '/products/all',
  PRODUCTS: '/',
  PRODUCT: '/',
  PRODUCT_DETAIL: '/products',
  RELATED_PRODUCTS: '/',
  FLASH_SELL_PRODUCTS: '/',
  BEST_SELLER_PRODUCTS: '/products/best-seller',
  BEST_DEALS: '/products/all/best-deals',
  NEW_ARRIVAL_PRODUCTS: '/',
  POPULAR_PRODUCTS: '/',
  COOKIES_PRODUCTS: '/',
  CHIPS_PRODUCTS: '/',
  POPCORN_JERKY_PRODUCTS: '/',
  ELETRONIC_PRODUCTS: '/',
  FASHION_PRODUCTS: '/',
  ELECTRONIC_CATEGORY: '/',
  PHONES_CATEGORY: '/',
  COMPUTER_CATEGORY: '/',
  CLOTH_CATEGORY: '/',
  SEARCH: '/products/search',
  CREATE_ORDER: '/orders',
  ORDERS: '/',
  ORDER: '/',
  ORDER_STATUS: '/',
  ADDRESS: '/',
  PAYMENT: '/',
  CONTACT: '/',
  SHOP: '/',
  SHOPS: '/',
  WISHLIST: '/',
  BLOGS: '/blogs',
  BLOGDETAILS: '/blogs',
  BLOGCATEGORIES: '/blog-categories',
  CATEGORY_BYID: '/product-categories',
  PRODUCTS_BYCATID: '/products',
  PRODUCT_BYTAG: '/products/tag-flex',
  ANNOUNCERS: '/toast-announcers'
};

// export const API_ENDPOINTS = {
//   LOGIN: '/login',
//   REGISTER: '/register',
//   LOGOUT: '/logout',
//   FORGET_PASSWORD: '/forget-password',
//   CATEGORIES: '/categories.json',
//   DIETARY: '/dietary.json',
//   BRANDS: '/brands.json',
//   PRODUCTS: '/products.json',
//   PRODUCT: '/product.json',
//   RELATED_PRODUCTS: '/related_products.json',
//   FLASH_SELL_PRODUCTS: '/products_flash_sell.json',
//   BEST_SELLER_PRODUCTS: '/products_best_seller.json',
//   NEW_ARRIVAL_PRODUCTS: '/products_new_arrival.json',
//   POPULAR_PRODUCTS: '/products_popular.json',
//   COOKIES_PRODUCTS: '/products_cookies.json',
//   CHIPS_PRODUCTS: '/products_chips.json',
//   POPCORN_JERKY_PRODUCTS: '/products_electronic.json',
//   ELETRONIC_PRODUCTS: '/products_electronic.json',
//   FASHION_PRODUCTS: '/products_fashion.json',
//   ELECTRONIC_CATEGORY: '/category_electronic.json',
//   PHONES_CATEGORY: '/category_phones.json',
//   COMPUTER_CATEGORY: '/category_computer.json',
//   CLOTH_CATEGORY: '/category_cloth.json',
//   SEARCH: '/search.json',
//   ORDERS: '/orders.json',
//   ORDER: '/order.json',
//   ORDER_STATUS: '/order-status.json',
//   ADDRESS: '/address.json',
//   PAYMENT: '/payment.json',
//   CONTACT: '/contact.json',
//   SHOP: '/shop.json',
//   SHOPS: '/shops.json',
//   WISHLIST: '/wishlist.json',
//   BLOGS: '/blog.json',
//   BLOGDETAILS: '/blogDetails.json',
//   BLOGCATEGORIES: '/blog-categories',
// };
