export const shops = [
  {
    id: 1,
    address: 'Jl. Percetakan Negara No. 66, Jayapura, Papua, Indonesia',
    phone: '+62-813-5653-0099',
    name: 'JayaElektronik Percetakan ',
    operationWeekday: '09:00 s.d 21:00 (Senin - Sabtu)',
    operationWeekend: 'Minggu Tutup',
    operationWeekdayEn: '09:00 s.d 21:00 (Monday - Saturday)',
    operationWeekendEn: 'Sunday Closed',
    slug: 'jaya-elektronik-jayapura',
    imageUrl: '/assets/images/shop/percetakan.jpg',
    map: 'https://maps.app.goo.gl/y2vwjR7cJCXmpw3o9',
  },
  {
    id: 2,
    address:
      'Jl. Raya Abepura - Samping ONYX Supermarket, Jayapura, Papua, Indonesia',
    phone: '+62-813-5653-0099',
    name: 'JayaElektronik Abepura',
    operationWeekday: '08:30 s.d 21:30 (Senin - Sabtu)',
    operationWeekend: '11:30 s.d 21:30 (Minggu / Libur)',
    operationWeekdayEn: '08:30 s.d 21:30 (Monday - Saturday)',
    operationWeekendEn: '11:30 s.d 21:30 (Sunday / Holiday)',
    slug: 'jaya-elektronik-abepura',
    imageUrl: '/assets/images/shop/abepura1.jpeg',
    map: 'https://maps.app.goo.gl/bLkdpuhy7yUcFTje8',
  },
  {
    id: 3,
    address:
      'Jl. Raya Sentani Ruko Mall Sentani City Square, Jayapura, Papua, Indonesia',
    phone: '+62-813-5653-0099',
    name: 'JayaElektronik Sentani',
    operationWeekday: '09:00 s.d 21:00 (Senin - Sabtu)',
    operationWeekend: 'Minggu Tutup',
    operationWeekdayEn: '09:00 s.d 21:00 (Monday - Saturday)',
    operationWeekendEn: 'Sunday Closed',
    slug: 'jaya-elektronik-sentani',
    imageUrl: '/assets/images/shop/sentani.jpg',
    map: 'https://maps.app.goo.gl/cPxgruRszrRzWvX58',
  },
];
